
name: Scheduled Cron Job 

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"   # runs every day at 02:00 UTC 
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
# env:
  # docker_path: File/docker/Dockerfile
  # image_name: my_image
  # issue_thread: 1

# permissions:
  # contents: read # to allow working with content of repository
  # issues: write # provide github cli action to update issues.

jobs:
  build:
    name: Ping Supabase 
    runs-on: ubuntu-latest
    environment: SUPABASE_ONBOARDING
    steps:
      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client
      - name: Connect to Supabase DB
        run: psql ${{ secrets.ADULT_DATA}} -c "SELECT * from adult_income LIMIT 5;"